version: '3'

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Rome
    devices:
      - ${ADAPTER_LOCATION}:/dev/ttyUSB0
    restart: always
    stop_grace_period: 60s
