version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    network_mode: "host"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/htpasswd:/etc/nginx/htpasswd:ro
      - ./data/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro        
    stop_grace_period: 1m

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    network_mode: "host"
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates:/etc/docker-gen/templates
      - ./data/conf.d:/etc/nginx/conf.d
    environment:
      - RESOLVERS=8.8.8.8 8.8.4.4
    command: "-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    stop_grace_period: 1m
    restart: always

  letsencrypt-companion:
    container_name: nginx-letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Rome
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
      - nginx-gen

# vim: ts=2 sw=2 et ai :
