version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ={{ cookiecutter.timezone }}
      - PUID=1000
      - GUID=1000
    restart: "{{ cookiecutter.default_container_restart_policy }}"
