version: '3'

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ={{ cookiecutter.timezone }}
    devices:
      - {{ cookiecutter.zigbee_usb_device }}:/dev/ttyUSB0
    restart: "{{ cookiecutter.default_container_restart_policy }}"
    stop_grace_period: 60s
