---
version: "3"
services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ cookiecutter.timezone }}
      - SUBDOMAINS={{ cookiecutter.duckdns_subdomain }}
      - TOKEN=${TOKEN}
      - LOG_FILE=true
    volumes:
      - ./data/config:/config
    restart: "{{ cookiecutter.default_container_restart_policy }}"
