- id: '1703088621962'
  alias: Accendi lampada letto
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 78393eb81eebf2cc5c5b6ac3d58b65ec
    type: action
    subtype: 'on'
    discovery_id: 0x84fd27fffe47a59e action_on
  condition: []
  action:
  - type: turn_on
    device_id: 74385ca5ff5852fdfbe0f3e5206cef12
    entity_id: 913d45c274325e4e5ca0f87271952c71
    domain: switch
  mode: single
- id: '1703088680571'
  alias: Spegni lampada letto
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 78393eb81eebf2cc5c5b6ac3d58b65ec
    type: action
    subtype: 'off'
    discovery_id: 0x84fd27fffe47a59e action_off
  condition: []
  action:
  - type: turn_off
    device_id: 74385ca5ff5852fdfbe0f3e5206cef12
    entity_id: 913d45c274325e4e5ca0f87271952c71
    domain: switch
  mode: single
