  version: '3'

  services:
    homeassistant:
      image: homeassistant/home-assistant:latest
      volumes:
        - ./config:/config
        - /etc/timezone:/etc/timezone:ro
      restart: always
      ports:
        - 8123:8123
        - 51827:51827
        - "5684:5683/udp"
      environment:
        - TZ=Europe/Rome
        - VIRTUAL_HOST=hass.krapps.it
        - VIRTUAL_PORT=8123
        - LETSENCRYPT_HOST=hass.krapps.it
        - LETSENCRYPT_EMAIL=kamir915@gmail.com
        - PUID=1000
        - GUID=1000
