#!/bin/bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

while getopts "dp" opt; do
  case $opt in
  d)
    alldown=1
    ;;
  p)
    pullonly=1
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  :)
    show_help
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

dop() {
  if [ -z "$1" ]; then exit 1; fi
  cd "$DIR/$1"
  if [ -f docker-compose.yml ]; then
    if [ -f disable -o "$alldown" = "1" ]; then
      echo "DOWN $1"
      docker-compose down -t 60 -v --remove-orphans || true
    else
      if [ "${pullonly}" == "1" ]; then
        echo "PULLING $1"
        docker-compose pull
      else
        echo "UP $1"
        docker-compose pull
        for s in $(docker-compose config --services); do
          if [ -f "$s/build" ] || [ -f "$s/buildonce" ]; then
            docker-compose build --pull "$s"
            if [ -f "$s/buildonce" ]; then rm -f "$s/buildonce"; fi
          fi
        done
        docker-compose up -d -t 60 --remove-orphans --always-recreate-deps
      fi
    fi
  else
    echo "ERROR Could not find any docker-compose.yml in $1."
    exit 1
  fi
  cd "$DIR"
}

if [ -z "$1" ]; then
  for d in *; do
    if [ -d "$d" ]; then
      dop "$d"
    fi
  done
else
  dop "$1"
fi